### PR TITLE
Add TXT record for SPF of Sendgrid

### PR DESCRIPTION
**Pull request by hmsk**
https://sendgrid.com/docs/Glossary/spf.html#-Already-have-an-SPF-record-for-your-domain

### CODE REVIEW

**Comment by hmsk** [comment]
@darashi review this please.

**Comment by darashi** [comment]
Looks good to me :eyeglasses:

**Comment by kakutani** [comment]
thanks~

**Comment by hmsk** [comment]
:sparkles: :space_invader: :sparkles:

**Pull request merged**
